# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^Page/~create/$",
        view=views.PageCreateView.as_view(),
        name='Page_create',
    ),
    url(
        regex="^Page/(?P<pk>\d+)/~delete/$",
        view=views.PageDeleteView.as_view(),
        name='Page_delete',
    ),
    url(
        regex="^Page/(?P<pk>\d+)/$",
        view=views.PageDetailView.as_view(),
        name='Page_detail',
    ),
    url(
        regex="^Page/(?P<pk>\d+)/~update/$",
        view=views.PageUpdateView.as_view(),
        name='Page_update',
    ),
    url(
        regex="^Page/$",
        view=views.PageListView.as_view(),
        name='Page_list',
    ),
	url(
        regex="^Section/~create/$",
        view=views.SectionCreateView.as_view(),
        name='Section_create',
    ),
    url(
        regex="^Section/(?P<pk>\d+)/~delete/$",
        view=views.SectionDeleteView.as_view(),
        name='Section_delete',
    ),
    url(
        regex="^Section/(?P<pk>\d+)/$",
        view=views.SectionDetailView.as_view(),
        name='Section_detail',
    ),
    url(
        regex="^Section/(?P<pk>\d+)/~update/$",
        view=views.SectionUpdateView.as_view(),
        name='Section_update',
    ),
    url(
        regex="^Section/$",
        view=views.SectionListView.as_view(),
        name='Section_list',
    ),
	url(
        regex="^PageSectionThroughModel/~create/$",
        view=views.PageSectionThroughModelCreateView.as_view(),
        name='PageSectionThroughModel_create',
    ),
    url(
        regex="^PageSectionThroughModel/(?P<pk>\d+)/~delete/$",
        view=views.PageSectionThroughModelDeleteView.as_view(),
        name='PageSectionThroughModel_delete',
    ),
    url(
        regex="^PageSectionThroughModel/(?P<pk>\d+)/$",
        view=views.PageSectionThroughModelDetailView.as_view(),
        name='PageSectionThroughModel_detail',
    ),
    url(
        regex="^PageSectionThroughModel/(?P<pk>\d+)/~update/$",
        view=views.PageSectionThroughModelUpdateView.as_view(),
        name='PageSectionThroughModel_update',
    ),
    url(
        regex="^PageSectionThroughModel/$",
        view=views.PageSectionThroughModelListView.as_view(),
        name='PageSectionThroughModel_list',
    ),
	url(
        regex="^SectionContent/~create/$",
        view=views.SectionContentCreateView.as_view(),
        name='SectionContent_create',
    ),
    url(
        regex="^SectionContent/(?P<pk>\d+)/~delete/$",
        view=views.SectionContentDeleteView.as_view(),
        name='SectionContent_delete',
    ),
    url(
        regex="^SectionContent/(?P<pk>\d+)/$",
        view=views.SectionContentDetailView.as_view(),
        name='SectionContent_detail',
    ),
    url(
        regex="^SectionContent/(?P<pk>\d+)/~update/$",
        view=views.SectionContentUpdateView.as_view(),
        name='SectionContent_update',
    ),
    url(
        regex="^SectionContent/$",
        view=views.SectionContentListView.as_view(),
        name='SectionContent_list',
    ),
	url(
        regex="^HtmlSectionContent/~create/$",
        view=views.HtmlSectionContentCreateView.as_view(),
        name='HtmlSectionContent_create',
    ),
    url(
        regex="^HtmlSectionContent/(?P<pk>\d+)/~delete/$",
        view=views.HtmlSectionContentDeleteView.as_view(),
        name='HtmlSectionContent_delete',
    ),
    url(
        regex="^HtmlSectionContent/(?P<pk>\d+)/$",
        view=views.HtmlSectionContentDetailView.as_view(),
        name='HtmlSectionContent_detail',
    ),
    url(
        regex="^HtmlSectionContent/(?P<pk>\d+)/~update/$",
        view=views.HtmlSectionContentUpdateView.as_view(),
        name='HtmlSectionContent_update',
    ),
    url(
        regex="^HtmlSectionContent/$",
        view=views.HtmlSectionContentListView.as_view(),
        name='HtmlSectionContent_list',
    ),
	url(
        regex="^TextSectionContent/~create/$",
        view=views.TextSectionContentCreateView.as_view(),
        name='TextSectionContent_create',
    ),
    url(
        regex="^TextSectionContent/(?P<pk>\d+)/~delete/$",
        view=views.TextSectionContentDeleteView.as_view(),
        name='TextSectionContent_delete',
    ),
    url(
        regex="^TextSectionContent/(?P<pk>\d+)/$",
        view=views.TextSectionContentDetailView.as_view(),
        name='TextSectionContent_detail',
    ),
    url(
        regex="^TextSectionContent/(?P<pk>\d+)/~update/$",
        view=views.TextSectionContentUpdateView.as_view(),
        name='TextSectionContent_update',
    ),
    url(
        regex="^TextSectionContent/$",
        view=views.TextSectionContentListView.as_view(),
        name='TextSectionContent_list',
    ),
	url(
        regex="^ImageSectionContent/~create/$",
        view=views.ImageSectionContentCreateView.as_view(),
        name='ImageSectionContent_create',
    ),
    url(
        regex="^ImageSectionContent/(?P<pk>\d+)/~delete/$",
        view=views.ImageSectionContentDeleteView.as_view(),
        name='ImageSectionContent_delete',
    ),
    url(
        regex="^ImageSectionContent/(?P<pk>\d+)/$",
        view=views.ImageSectionContentDetailView.as_view(),
        name='ImageSectionContent_detail',
    ),
    url(
        regex="^ImageSectionContent/(?P<pk>\d+)/~update/$",
        view=views.ImageSectionContentUpdateView.as_view(),
        name='ImageSectionContent_update',
    ),
    url(
        regex="^ImageSectionContent/$",
        view=views.ImageSectionContentListView.as_view(),
        name='ImageSectionContent_list',
    ),
	url(
        regex="^LinkSectionContent/~create/$",
        view=views.LinkSectionContentCreateView.as_view(),
        name='LinkSectionContent_create',
    ),
    url(
        regex="^LinkSectionContent/(?P<pk>\d+)/~delete/$",
        view=views.LinkSectionContentDeleteView.as_view(),
        name='LinkSectionContent_delete',
    ),
    url(
        regex="^LinkSectionContent/(?P<pk>\d+)/$",
        view=views.LinkSectionContentDetailView.as_view(),
        name='LinkSectionContent_detail',
    ),
    url(
        regex="^LinkSectionContent/(?P<pk>\d+)/~update/$",
        view=views.LinkSectionContentUpdateView.as_view(),
        name='LinkSectionContent_update',
    ),
    url(
        regex="^LinkSectionContent/$",
        view=views.LinkSectionContentListView.as_view(),
        name='LinkSectionContent_list',
    ),
	]
